name: "nightly"

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:

  spec:
    strategy:
      fail-fast: false
      matrix:
        ruby_version:
          - '3.2'
        runs_on:
          - 'ubuntu-latest'
          - 'windows-latest'

    name: "Spec : ${{ matrix.runs_on }} Ruby ${{ matrix.ruby_version }}"
    runs-on: ${{ matrix.runs_on }}
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby_version }}
          bundler-cache: true
      - name: Run specs
        run: bundle exec rake gem_revendor test_languageserver test_languageserver_sidecar test_debugserver

  acceptance:
    strategy:
      fail-fast: false
      matrix:
        ruby_version:
          - '3.2'
        runs_on:
          - 'ubuntu-latest'
          - 'windows-latest'

    name: "Acceptance : ${{ matrix.runs_on }} Ruby ${{ matrix.ruby_version }}"
    runs-on: ${{ matrix.runs_on }}
    env:
      PUPPET_GEM_VERSION: '~> 8.0'
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby_version }}
          bundler-cache: true
      - name: Run acceptance tests
        run: bundle exec rake gem_revendor acceptance_languageserver

  build:
    strategy:
      fail-fast: false
      matrix:
        ruby_version:
          - '3.2'
    name: "Build Editor Service (Ruby ${{ matrix.ruby_version }})"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby_version }}
          bundler-cache: true
      - name: Set build version
        run: echo '99.99.0-gh.${{ github.run_number }}' > lib/puppet_editor_services/VERSION
      - name: Run rake gem_revendor build
        run: bundle exec rake gem_revendor build
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v4
        with:
          name: openvox-editor-services
          path: pkg/*.zip
          retention-days: 2
  
